project:
  type: website            # Project type: "website" for multi-page website projects
  output-dir: _site        # Output directory for rendered website files
  # render:                  # Specify files or patterns to render (default: all files)
  # lib-dir:                 # Directory for supporting JS, CSS, and other library assets
  preview:
    port: 3000                  # Port number for local preview server (default random 3000-8000)
    browser: true               # Whether to open browser on preview (true/false)
    host: localhost             # Host address for preview server (e.g., 'localhost')

metadata-files:
  - _website.yml
  - _format.yml
  - _brand.yml

execute:
  cache: true
  freeze: auto

filters:
  - quarto-ext/fontawesome

lightbox: auto

highlight-style: breezedark

editor:
    render-on-save: true


  # body-header:             # Markdown to insert at the top of each page body (below title)
  # body-footer:             # Markdown to insert at the bottom of each page body
  # margin-header:           # Markdown content above the margin column content
  # margin-footer:           # Markdown content below the margin column content

  # bread-crumbs:            # Show breadcrumb navigation for subpages (true/false)

  # comments:                # Configuration for commenting system (e.g., Disqus, Giscus)
  # open-graph:              # Open Graph metadata options for Facebook/LinkedIn sharing
    # title:                 # OG title override (default: page title)
    # description:           # OG description override
    # image:                 # OG image override
  # other-links:             # List of additional links shown below table of contents
  # code-links:              # Links to code/repository displayed with pages
  # drafts:                  # List of document files treated as drafts (excluded by default)
  # draft-mode:              # How to handle drafts: ignore, render, or publish


